"""Estimates -> the site's JSON records, and the takeaway sentences.

Nothing here reads files, the network or the clock. Rates and changes are in percent, as
the sources publish them; elasticities are unitless; months are ``"YYYY-MM"`` and years
``"YYYY"``. An estimate is ``Est = {est, se, t, p, lo, hi}`` with a 95% t-based interval.
Every float is rounded to 6 decimals and NaN becomes ``null`` (:func:`clean`).

Every takeaway sentence is generated by a template from the numbers of its own page, after
rounding, so ``pipeline.validate`` can run the same template on the published JSON and
check that the sentence still matches. The thresholds that choose between wordings are the
constants below. Negative numbers get a typographic minus (−).
"""

from __future__ import annotations

import math
from collections.abc import Mapping, Sequence
from typing import Any

import numpy as np
import pandas as pd

from . import SCHEMA_VERSION
from .models import BORDER as BORDER_WINDOW
from .models import GFC, HORIZON, Est

DECIMALS = 6
MONTH_NAMES = ("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

# thresholds of the takeaway templates
TIMING_SHARE = 0.25  # post-2017 months 0-3 below this share of the 12-month effect
FIT_WORDS = ((0.65, "most"), (0.4, "about half"), (0.25, "about a third"), (0.1, "a small part"))
GAP_SPREAD = 1.5  # highest / lowest ratio of Mongolia's coal price to the benchmark
BIG_DEPRECIATION = 15.0  # percent rise in MNT per US dollar, December to December
SMALL_SAMPLE = 30  # years; below this the growth sentence says "treat as descriptive"
FORECAST_SPREAD = 1.0  # pp; within this the later WEO years are summed up as "about x%"

EPISODES = (
    ("global financial crisis", *GFC),
    ("commodity bust", "2011-01", "2016-12"),
    ("border closures", *BORDER_WINDOW),
)
BORDER = {"start": BORDER_WINDOW[0], "end": BORDER_WINDOW[1]}
COAL_MONTHLY_FROM = "2017-01"
CONTEXT_FROM = "2008-01"
PAGES = (
    ("copper", "copper and the tugrik"),
    ("coal", "coal is a volume story"),
    ("prices", "does a weaker tugrik raise prices?"),
    ("growth", "growth follows export prices a year later"),
)


# -- numbers and text ----------------------------------------------------------------------
def num(x: Any) -> float | None:
    """``x`` rounded to 6 decimals for JSON; None if it is missing or not finite."""
    if x is None:
        return None
    x = float(x)
    if not math.isfinite(x):
        return None
    return round(x, DECIMALS) + 0.0  # + 0.0 turns -0.0 into 0.0


def clean(obj: Any) -> Any:
    """A copy of ``obj`` fit for JSON: floats rounded (:func:`num`), NumPy scalars as
    Python ones, tuples as lists."""
    if isinstance(obj, Mapping):
        return {str(k): clean(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [clean(v) for v in obj]
    if isinstance(obj, (bool, np.bool_)):
        return bool(obj)
    if isinstance(obj, (int, np.integer)):
        return int(obj)
    if isinstance(obj, (float, np.floating)):
        return num(obj)
    return obj


def signed(x: float, spec: str) -> str:
    """``format(x, spec)`` with a typographic minus (−) for negative numbers.

    A number that rounds to zero is written without a sign ("0.0", not "−0.0").
    """
    text = format(x, spec)
    if not any(c in "123456789" for c in text):
        text = format(abs(x) * 0, spec.replace("+", ""))
    return text.replace("-", "−")


def month_name(month: str) -> str:
    """``"2026-08"`` -> ``"Aug 2026"``."""
    return f"{MONTH_NAMES[int(month[5:7]) - 1]} {month[:4]}"


def listing(items: Sequence[str]) -> str:
    """``["a", "b", "c"]`` -> ``"a, b and c"``."""
    items = list(items)
    return items[0] if len(items) == 1 else ", ".join(items[:-1]) + " and " + items[-1]


def est(e: Est | None) -> dict[str, float] | None:
    if e is None:
        return None
    return {"est": e.est, "se": e.se, "t": e.t, "p": e.p, "lo": e.lo, "hi": e.hi}


def excludes_zero(e: Mapping[str, float]) -> bool:
    """True when a published estimate's 95% interval does not contain zero."""
    return e["lo"] > 0 or e["hi"] < 0


def values(s: pd.Series, index: Sequence[str]) -> list[float | None]:
    """``s`` at each date of ``index`` (None where it has no value)."""
    return [num(s.get(d)) for d in index]


# -- copper --------------------------------------------------------------------------------
def copper_page(copper: Mapping[str, dict], fit12: Mapping[str, Any]) -> dict[str, Any]:
    """``copper.json`` from :func:`pipeline.models.copper_dl12` and ``fx_fit12``."""
    fit = fit12["fit"]
    page = {
        "schema_version": SCHEMA_VERSION,
        "horizons": list(range(HORIZON + 1)),
        "samples": [
            {
                "id": r["sample"].id,
                "label": r["sample"].label,
                "start": r["fit"].start,
                "end": r["fit"].end,
                "nobs": r["fit"].nobs,
                "maxlags": r["fit"].maxlags,
                "r2": r["fit"].r2,
                "copper": [est(e) for e in r["copper"]],
                "coal_h12": est(r["coal_h12"]),
            }
            for r in copper.values()
        ],
        "controls": {"usd": est(copper["full"]["usd"]), "cny": est(copper["full"]["cny"])},
        "fit12": {
            "months": [str(p) for p in fit.periods],
            "actual_pct": list(fit12["actual"]),
            "fitted_pct": list(fit12["fitted"]),
            "nobs": fit.nobs,
            "r2": fit.r2,
            "maxlags": fit.maxlags,
            "copper_t6": est(fit12["copper_t6"]),
            "coal_t6": est(fit12["coal_t6"]),
            "usd": est(fit12["usd"]),
        },
        "episodes": [{"label": a, "start": b, "end": c} for a, b, c in EPISODES],
    }
    page = clean(page)
    page["takeaway"] = copper_takeaway(page)
    page["takeaway_fit"] = copper_fit_takeaway(page)
    return page


def sample(page: Mapping[str, Any], sample_id: str) -> dict[str, Any]:
    return next(s for s in page["samples"] if s["id"] == sample_id)


def copper_timing(page: Mapping[str, Any]) -> bool:
    """Since 2017, is there a significant weakening over 12 months (a negative sum) with
    little of it in months 0-3?

    Not when the full sample shows a significant strengthening: the clause would then
    describe the opposite of the sentence before it.
    """
    full = sample(page, "full")["copper"][12]
    post = sample(page, "post2017")["copper"]
    weakening = post[12]["est"] < 0 and excludes_zero(post[12])
    contradicted = full["est"] > 0 and excludes_zero(full)
    late = abs(post[3]["est"]) < TIMING_SHARE * abs(post[12]["est"])
    return weakening and late and not contradicted


def copper_takeaway(page: Mapping[str, Any]) -> str:
    """The copper page's sentence: the 12-month effect of a 10% copper fall on the tugrik.

    Significant (the full-sample interval excludes zero): "…followed by a 2.3% weaker
    tugrik…". Not: "…cannot be told apart from zero". Then a timing clause when
    :func:`copper_timing`, and a coal clause when the upper end of the coal interval is at
    least zero (world coal prices do not strengthen the tugrik).
    """
    full = sample(page, "full")
    h12 = full["copper"][12]
    years = f"{full['start'][:4]}–{full['end'][:4]}"
    if excludes_zero(h12):
        size = abs(10 * h12["est"])
        lo, hi = sorted(abs(10 * h12[k]) for k in ("lo", "hi"))
        direction = "weaker" if h12["est"] < 0 else "stronger"
        text = (
            f"A 10% fall in the copper price has been followed by a {size:.1f}% {direction} "
            f"tugrik over the next 12 months (95% CI {lo:.1f}–{hi:.1f}%, {years})."
        )
    else:
        lo, hi = sorted(-10 * h12[k] for k in ("lo", "hi"))
        text = (
            "The tugrik's move in the 12 months after a 10% fall in the copper price, "
            f"{signed(-10 * h12['est'], '+.1f')}% (positive is weaker), cannot be told apart "
            f"from zero (95% CI {signed(lo, '.1f')} to {signed(hi, '.1f')}%, {years})."
        )
    if copper_timing(page):
        post = sample(page, "post2017")["copper"]
        lo, hi = sorted(abs(10 * post[12][k]) for k in ("lo", "hi"))
        text += (
            f" Since 2017 it arrives after month 3: of the {abs(10 * post[12]['est']):.1f}% "
            f"(95% CI {lo:.1f}–{hi:.1f}%), {signed(-10 * post[3]['est'], '.1f')}% comes in "
            "months 0–3."
        )
    coal = full["coal_h12"]
    if coal["hi"] >= 0:
        why = "the wrong sign" if coal["est"] > 0 else "not significant"
        text += f" World coal prices show no such effect ({signed(coal['est'], '+.2f')}, {why})."
    return text


def copper_fit_takeaway(page: Mapping[str, Any]) -> str:
    """How much of the tugrik's year-on-year moves prices six months earlier account for."""
    r2 = page["fit12"]["r2"]
    share = next((words for floor, words in FIT_WORDS if r2 >= floor), "almost none")
    return (
        f"Copper and coal prices six months earlier and the dollar account for {share} of "
        f"the tugrik's year-on-year moves (R² = {r2:.2f})."
    )


# -- coal ----------------------------------------------------------------------------------
def coal_page(
    annual: pd.DataFrame, volume_kt: pd.Series, unit_value: pd.Series, benchmark: pd.Series
) -> dict[str, Any]:
    """``coal.json`` from :func:`pipeline.models.coal_decomp` and the monthly series.

    ``dlog_unit_value`` is published as ``dlog_value - dlog_volume`` of the rounded numbers,
    so the identity holds exactly in the published file too.
    """
    rows = []
    for year, r in annual.iterrows():
        dv, dq = num(r["dlog_value"]), num(r["dlog_volume"])
        rows.append(
            {
                "year": str(year),
                "partial": bool(r["months"] < 12),
                "through": r["through"],
                "value_musd": r["value_musd"],
                "volume_mt": r["volume_mt"],
                "unit_value_usd_t": r["unit_value_usd_t"],
                "benchmark_usd_t": r["benchmark_usd_t"],
                "dlog_value": dv,
                "dlog_volume": dq,
                "dlog_unit_value": None if dv is None or dq is None else num(dv - dq),
                "volume_vs_2019_pct": r["volume_vs_2019_pct"],
            }
        )
    months = [m for m in volume_kt.index if m >= COAL_MONTHLY_FROM]
    page = {
        "schema_version": SCHEMA_VERSION,
        "annual": rows,
        "monthly": {
            "months": months,
            "volume_mt": [num(volume_kt[m] / 1e3) for m in months],
            "unit_value_usd_t": values(unit_value, months),
            "benchmark_usd_t": values(benchmark, months),
        },
        "border": dict(BORDER),
    }
    page = clean(page)
    page["takeaway"] = coal_takeaway(page)
    page["takeaway_gap"] = coal_gap_takeaway(page)
    return page


def coal_takeaway(page: Mapping[str, Any]) -> str:
    """Coal income against the border: the lowest tonnage (against 2019) in a year of the
    closures, the latest full year, and the price per tonne in both.

    It opens "Coal income followed the Chinese border" when, from the first year of the
    closures on, tonnage moved more than the price per tonne (the sums of the absolute log
    changes); otherwise "Coal income followed prices more than the border".
    """
    full = [r for r in page["annual"] if not r["partial"]]
    first, last = page["border"]["start"][:4], page["border"]["end"][:4]
    during = [r for r in full if first <= r["year"] <= last]
    since = [r for r in full if r["year"] >= first and r["dlog_volume"] is not None]
    if not during or not since:
        latest = full[-1]
        return (
            f"In {latest['year']} Mongolia exported {latest['volume_mt']:.1f} Mt of coal at "
            f"{latest['unit_value_usd_t']:.0f} USD/t."
        )
    trough = min(during, key=lambda r: r["volume_vs_2019_pct"])
    latest = full[-1]
    volume_led = sum(abs(r["dlog_volume"]) for r in since) >= sum(
        abs(r["dlog_unit_value"]) for r in since
    )
    if volume_led:
        lead = "Coal income followed the Chinese border"
    else:
        lead = "Coal income followed prices more than the border"
    verb = "reached" if latest["volume_vs_2019_pct"] >= 100 else "were back to only"
    return (
        f"{lead}: shipments fell to {trough['volume_vs_2019_pct']:.0f}% of their 2019 tonnage "
        f"in {trough['year']} and {verb} {latest['volume_vs_2019_pct']:.0f}% in "
        f"{latest['year']}, while Mongolia's price per tonne went from "
        f"{trough['unit_value_usd_t']:.0f} to {latest['unit_value_usd_t']:.0f} USD/t."
    )


def coal_gap_takeaway(page: Mapping[str, Any]) -> str:
    """Mongolia's coal price against the Australian benchmark: the latest month, and the
    range of their ratio over the monthly panel. A range wider than :data:`GAP_SPREAD`
    (highest over lowest) means the benchmark is a poor guide."""
    m = page["monthly"]
    pairs = [
        (month, uv, bm)
        for month, uv, bm in zip(
            m["months"], m["unit_value_usd_t"], m["benchmark_usd_t"], strict=True
        )
        if uv is not None and bm is not None and bm > 0
    ]
    if not pairs:
        return "There is no month with both Mongolia's coal price and the benchmark."
    month, uv, bm = pairs[-1]
    ratios = [100 * u / b for _, u, b in pairs]
    low, high = min(ratios), max(ratios)
    text = (
        f"Mongolia's coal fetched ${uv:.0f}/t in {month_name(month)} against ${bm:.0f} for the "
        f"Australian benchmark. Since {pairs[0][0][:4]} it has sold for between {low:.0f}% "
        f"and {high:.0f}% of the benchmark"
    )
    if high > GAP_SPREAD * low:
        return text + ", so world coal prices say little about what Mongolia earns."
    return text + ", so the two have moved together."


# -- prices --------------------------------------------------------------------------------
SPEC_LABELS = {
    "dl": "plain distributed lag (B1)",
    "preferred": "with CPI persistence, oil and copper (B3, preferred)",
}


def prices_page(
    dl: Mapping[str, Any],
    preferred: Mapping[str, Any],
    context: Mapping[str, pd.Series],
    years: pd.DataFrame,
    weo: Mapping[str, Any],
) -> dict[str, Any]:
    """``prices.json`` from :func:`pipeline.models.passthrough_dl` and ``passthrough_pref``.

    ``context`` holds the monthly ``cpi_yoy_pct``, ``policy_rate_pct`` and ``fx_12m_pct``
    series; ``years`` has ``fx_dec_dec_pct`` and ``copper_avg_pct`` by year (percent
    changes, not log changes); ``weo`` is ``{vintage, years, cpi_avg_pct}``.
    """

    def spec(spec_id: str, r: Mapping[str, Any]) -> dict[str, Any]:
        fit = r["fit"]
        return {
            "id": spec_id,
            "label": SPEC_LABELS[spec_id],
            "start": fit.start,
            "end": fit.end,
            "nobs": fit.nobs,
            "maxlags": fit.maxlags,
            "r2": fit.r2,
            "cum": [est(e) for e in r["cum"]],
            "long_run": est(r["long_run"]),
            "oil_sum": est(r["oil_sum"]),
            "copper_sum": est(r["copper_sum"]),
            "rho": r["rho"],
        }

    start = max(CONTEXT_FROM, min(s.index[0] for s in context.values()))
    end = max(s.index[-1] for s in context.values())
    months = [p.strftime("%Y-%m") for p in pd.period_range(start, end, freq="M")]
    page = {
        "schema_version": SCHEMA_VERSION,
        "horizons": list(range(HORIZON + 1)),
        "specs": [spec("dl", dl), spec("preferred", preferred["full"])],
        "subsamples": [
            {
                "id": r["sample"].id,
                "label": r["sample"].label,
                "start": r["fit"].start,
                "end": r["fit"].end,
                "nobs": r["fit"].nobs,
                "h12": est(r["cum"][HORIZON]),
                "long_run": est(r["long_run"]),
            }
            for r in preferred["subsamples"]
        ],
        "context": {"months": months} | {k: values(s, months) for k, s in context.items()},
        "years": [
            {
                "year": str(y),
                "fx_dec_dec_pct": r["fx_dec_dec_pct"],
                "copper_avg_pct": r["copper_avg_pct"],
            }
            for y, r in years.iterrows()
        ],
        "weo": dict(weo),
    }
    page = clean(page)
    page["takeaway"] = prices_takeaway(page)
    page["takeaway_context"] = prices_context_takeaway(page)
    return page


def pct0(x: float) -> str:
    """A share as a whole percentage with a typographic minus: 0.129 -> "13"."""
    return signed(100 * x, ".0f")


def prices_takeaway(page: Mapping[str, Any]) -> str:
    """The 12-month pass-through of the preferred specification (B3).

    A positive estimate reads "About 13% of a depreciation shows up…"; when its interval
    includes zero it adds "but the data can't rule out zero or 28%". An estimate of zero or
    less whose interval includes zero "cannot be told apart from zero", and the sentence
    says how much the data can't rule out; one whose interval lies below zero says prices
    have fallen, not risen, after depreciations.
    """
    pref = next(s for s in page["specs"] if s["id"] == "preferred")
    h12 = pref["cum"][HORIZON]
    ci = f"95% CI {pct0(h12['lo'])}% to {pct0(h12['hi'])}%"
    if h12["est"] > 0:
        text = (
            f"About {pct0(h12['est'])}% of a depreciation shows up in consumer prices within a year"
        )
        if excludes_zero(h12):
            return f"{text} ({ci})."
        return f"{text}, but the data can't rule out zero or {pct0(h12['hi'])}% ({ci})."
    if excludes_zero(h12):
        return (
            "Consumer prices have fallen, not risen, after depreciations: "
            f"{pct0(h12['est'])}% of a depreciation within a year ({ci})."
        )
    return (
        "The share of a depreciation that shows up in consumer prices within a year cannot "
        f"be told apart from zero (estimate {pct0(h12['est'])}%); the data can't rule out up "
        f"to {pct0(h12['hi'])}% ({ci})."
    )


def prices_context_takeaway(page: Mapping[str, Any]) -> str:
    """Why the raw link is weak: the years in which MNT per US dollar rose at least
    :data:`BIG_DEPRECIATION` percent (December to December), how many of them saw the
    average copper price fall, and the plain distributed lag's 12-month pass-through (B1).

    When most big depreciations came with falling copper prices and B1 cannot be told from
    zero, the sentence names that as one reason.
    """
    big = [
        r
        for r in page["years"]
        if r["fx_dec_dec_pct"] is not None and r["fx_dec_dec_pct"] >= BIG_DEPRECIATION
    ]
    dl = next(s for s in page["specs"] if s["id"] == "dl")["cum"][HORIZON]
    raw = (
        f"{pct0(dl['est'])}% of a depreciation within a year, "
        f"95% CI {pct0(dl['lo'])}% to {pct0(dl['hi'])}%"
    )
    if excludes_zero(dl):
        link = f"The raw link from the tugrik to prices is {raw}."
    else:
        link = f"The raw link from the tugrik to prices ({raw}) cannot be told apart from zero."
    if not big:
        return (
            f"MNT per US$ never rose {BIG_DEPRECIATION:.0f}% or more in a year (December to "
            f"December) in these data. {link}"
        )
    falling = [r for r in big if r["copper_avg_pct"] is not None and r["copper_avg_pct"] < 0]
    how_many = "all" if len(falling) == len(big) else f"{len(falling)} of the {len(big)}"
    text = (
        f"The big depreciations ({listing([r['year'] for r in big])}: MNT per US$ up "
        f"{BIG_DEPRECIATION:.0f}% or more, December to December) {how_many} came in years of "
        "falling copper prices."
    )
    if 2 * len(falling) > len(big) and not excludes_zero(dl):
        link = (
            f"That is one reason the raw link from the tugrik to prices ({raw}) cannot be "
            "told apart from zero."
        )
    return f"{text} {link}"


# -- growth --------------------------------------------------------------------------------
def growth_page(
    growth: Mapping[str, Any],
    weights_source: pd.Series,
    weo: Mapping[str, Any],
    boom_bust: pd.DataFrame,
) -> dict[str, Any]:
    """``growth.json`` from :func:`pipeline.models.growth`.

    ``annual.weights`` are each year's own export shares (the export-mix chart);
    ``mxpi_pct`` of a year uses the previous year's.
    """
    fit, data, weights = growth["fit"], growth["data"], growth["weights"]
    annual = []
    for year in weights.index:
        p = pd.Period(year, freq="Y")
        row = data.loc[p] if p in data.index else None
        annual.append(
            {
                "year": year,
                "gdp_growth_pct": None if row is None else row["growth"],
                "mxpi_pct": None if row is None else row["mxpi"],
                "mxpi_lag_pct": None if row is None else row["mxpi_L1"],
                "weights": weight_row(weights.loc[year]),
                "weights_source": weights_source[year],
            }
        )
    page = {
        "schema_version": SCHEMA_VERSION,
        "annual": annual,
        "fit": {
            "start": fit.start,
            "end": fit.end,
            "nobs": fit.nobs,
            "maxlags": fit.maxlags,
            "r2": fit.r2,
            "const": est(growth["const"]),
            "mxpi": est(growth["mxpi"]),
            "mxpi_l1": est(growth["mxpi_l1"]),
            "sum": est(growth["sum"]),
            "p_l1_nonrobust": growth["p_l1_nonrobust"],
            "p_l1_hc1": growth["p_l1_hc1"],
        },
        "robustness": [
            {"drop": r["drop"], "nobs": r["fit"].nobs, "mxpi_l1": est(r["mxpi_l1"])}
            for r in growth["robustness"]
        ],
        "weo": dict(weo),
        "boom_bust": [{"year": str(y), **r} for y, r in boom_bust.to_dict("index").items()],
    }
    page = clean(page)
    page["takeaway"] = growth_takeaway(page)
    page["takeaway_weo"] = growth_weo_takeaway(page)
    page["takeaway_mix"] = growth_mix_takeaway(page)
    return page


def weight_row(shares: pd.Series) -> dict[str, float]:
    """One year's shares rounded to 6 decimals, the largest taking up the rounding so that
    the published shares still sum to 1. (The unrounded shares sum to 1 within 1e-9;
    :func:`pipeline.transform.mxpi_weights` checks that.)"""
    rounded = {g: num(v) for g, v in shares.items()}
    top = max(rounded, key=lambda g: rounded[g])
    rounded[top] = num(1.0 - sum(v for g, v in rounded.items() if g != top))
    return rounded


def growth_takeaway(page: Mapping[str, Any]) -> str:
    """Growth the year after a 10% rise in the export-price index (C2's mxpi(t-1)).

    Significant with HAC: "…followed by about 0.85 pp faster growth the next year"; not:
    "…cannot be told apart from zero". With fewer than :data:`SMALL_SAMPLE` years it adds
    "treat as descriptive", and it always gives the non-robust p-value too.
    """
    fit = page["fit"]
    b = fit["mxpi_l1"]
    detail = (
        f"{fit['nobs']} years; t = {signed(b['t'], '.1f')} with HAC, "
        f"p = {fit['p_l1_nonrobust']:.3f} without"
    )
    if fit["nobs"] < SMALL_SAMPLE:
        detail += " — treat as descriptive"
    if excludes_zero(b):
        pace = "faster" if b["est"] > 0 else "slower"
        return (
            f"A 10% rise in Mongolia's export prices has been followed by about "
            f"{abs(10 * b['est']):.2f} pp {pace} growth the next year ({detail})."
        )
    return (
        "Growth the year after a 10% rise in Mongolia's export prices, "
        f"{signed(10 * b['est'], '+.2f')} pp, cannot be told apart from zero ({detail})."
    )


def growth_weo_takeaway(page: Mapping[str, Any]) -> str:
    """The IMF's forecast: the first year, then the rest summed up as "about x% a year" when
    they lie within :data:`FORECAST_SPREAD` of each other, or as a range."""
    years, rates = page["weo"]["years"], page["weo"]["gdp_growth_pct"]
    if not years:
        return "The IMF's growth forecasts are not available."
    text = f"The IMF expects {signed(rates[0], '.1f')}% in {years[0]}"
    rest = rates[1:]
    if not rest:
        return text + "."
    if max(rest) - min(rest) <= FORECAST_SPREAD:
        return text + f" and about {signed(sum(rest) / len(rest), '.0f')}% a year after that."
    return text + (
        f" and between {signed(min(rest), '.1f')}% and {signed(max(rest), '.1f')}% a year "
        "after that."
    )


def growth_mix_takeaway(page: Mapping[str, Any]) -> str:
    """Coal's share of the six goods: the first year, its peak, and the latest split."""
    rows = page["annual"]
    first, last = rows[0], rows[-1]
    peak = max(rows, key=lambda r: r["weights"]["coal"])
    start = first["weights"]["coal"]
    was = "none" if start < 0.005 else f"{100 * start:.0f}%"
    return (
        f"Coal went from {was} of these exports in {first['year']} to "
        f"{100 * peak['weights']['coal']:.0f}% in {peak['year']}; in {last['year']}, copper "
        f"and coal split them {100 * last['weights']['copper']:.0f}/"
        f"{100 * last['weights']['coal']:.0f}."
    )


# -- overview ------------------------------------------------------------------------------
SPARK = 36


def spark(s: pd.Series) -> dict[str, list]:
    """The last 36 observations of a series."""
    tail = s.iloc[-SPARK:]
    return {"dates": list(tail.index), "values": [num(v) for v in tail]}


def tile(
    tile_id: str,
    label: str,
    s: pd.Series,
    unit: str,
    source: str,
    status: str,
    change: Mapping[str, Any] | None = None,
    detail: Mapping[str, Any] | None = None,
    value: float | None = None,
    period: str | None = None,
    history: pd.Series | None = None,
) -> dict[str, Any]:
    """One overview tile: the latest value of ``s`` (or ``value`` at ``period``) with a
    sparkline of ``history`` (default ``s``)."""
    return {
        "id": tile_id,
        "label": label,
        "value": num(s.iloc[-1] if value is None else value),
        "unit": unit,
        "period": s.index[-1] if period is None else period,
        "change": None if change is None else clean(dict(change)),
        "detail": None if detail is None else clean(dict(detail)),
        "spark": spark(s if history is None else history),
        "source": source,
        "status": status,
    }


def year_ago(s: pd.Series) -> tuple[str, float] | None:
    """The observation 12 months before a monthly series' last one, if it has one."""
    last = pd.Period(s.index[-1], freq="M")
    month = (last - 12).strftime("%Y-%m")
    return (month, float(s[month])) if month in s.index else None


def pct_change(s: pd.Series) -> dict[str, Any] | None:
    ago = year_ago(s)
    if ago is None:
        return None
    return {
        "value": 100 * (s.iloc[-1] / ago[1] - 1),
        "unit": "%",
        "label": f"vs {month_name(ago[0])}",
    }


def pp_change(s: pd.Series) -> dict[str, Any] | None:
    ago = year_ago(s)
    if ago is None:
        return None
    return {"value": s.iloc[-1] - ago[1], "unit": "pp", "label": f"vs {month_name(ago[0])}"}


def overview(tiles: list[dict[str, Any]], pages: Mapping[str, Mapping[str, Any]]) -> dict[str, Any]:
    """``overview.json``: the tiles and one card per page with its takeaway."""
    return {
        "tiles": tiles,
        "cards": [
            {"page": page_id, "title": title, "takeaway": pages[page_id]["takeaway"]}
            for page_id, title in PAGES
        ],
    }


# -- the templates, for pipeline.validate --------------------------------------------------
TAKEAWAYS = {
    "copper": {"takeaway": copper_takeaway, "takeaway_fit": copper_fit_takeaway},
    "coal": {"takeaway": coal_takeaway, "takeaway_gap": coal_gap_takeaway},
    "prices": {"takeaway": prices_takeaway, "takeaway_context": prices_context_takeaway},
    "growth": {
        "takeaway": growth_takeaway,
        "takeaway_weo": growth_weo_takeaway,
        "takeaway_mix": growth_mix_takeaway,
    },
}
